# Generated by Django 4.2.23 on 2025-07-31 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('headers_json', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('from_cache', models.BooleanField(default=False)),
                ('body_path', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='request.requestqueue')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['request'], name='response_re_request_51d6f8_idx'), models.Index(fields=['status_code'], name='response_re_status__b565bf_idx'), models.Index(fields=['fetched_at'], name='response_re_fetched_73b134_idx'), models.Index(fields=['content_hash'], name='response_re_content_eadc4d_idx')],
            },
        ),
    ]
