# Generated by Django 4.2.23 on 2025-07-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expr', models.CharField(help_text="Cron expression (e.g., '0 */6 * * *' for every 6 hours)", max_length=100)),
                ('timezone', models.CharField(default='Australia/Brisbane', help_text='Timezone for schedule execution', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='spider.spider')),
            ],
            options={
                'ordering': ['next_run_at', '-created_at'],
                'indexes': [models.Index(fields=['spider', 'enabled'], name='schedule_sc_spider__0364b4_idx'), models.Index(fields=['enabled', 'next_run_at'], name='schedule_sc_enabled_7038de_idx'), models.Index(fields=['next_run_at'], name='schedule_sc_next_ru_1407c9_idx')],
            },
        ),
    ]
