# Generated by Django 4.2.23 on 2025-07-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Session label (e.g., 'default', 'sellerA')", max_length=100, null=True)),
                ('cookies_json', models.JSONField(blank=True, help_text='Cookies for this session', null=True)),
                ('headers_json', models.JSONField(blank=True, help_text='Headers for this session', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this session expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='spider.spider')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['spider'], name='session_ses_spider__54b3d7_idx'), models.Index(fields=['spider', 'label'], name='session_ses_spider__c96c15_idx'), models.Index(fields=['valid_until'], name='session_ses_valid_u_290dd0_idx')],
                'unique_together': {('spider', 'label')},
            },
        ),
    ]