# Generated by Django 4.2.23 on 2025-07-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='spider.spider')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['spider', 'status'], name='job_job_spider__ffc136_idx')],
            },
        ),
    ]
