# Generated by Django 4.2.23 on 2025-07-31 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('headers_json', models.JSONField(blank=True, null=True)),
                ('body_blob', models.BinaryField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('retries', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('fingerprint', models.CharField(max_length=64)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='job.job')),
            ],
            options={
                'ordering': ['-priority', 'scheduled_at'],
                'indexes': [models.Index(fields=['job', 'status', '-priority', 'scheduled_at'], name='idx_job_status_priority'), models.Index(fields=['status', 'scheduled_at'], name='request_req_status_8212a6_idx'), models.Index(fields=['fingerprint'], name='request_req_fingerp_787383_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestqueue',
            constraint=models.UniqueConstraint(fields=('job', 'fingerprint'), name='unique_job_fingerprint'),
        ),
    ]
