# Generated by Django 4.2.23 on 2025-08-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='advanced_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='execution_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='output_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='retry_policy_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='target_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
