# Generated by Django 4.2.23 on 2025-07-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(help_text='Proxy URI (scheme://user:pass@host:port)', max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this proxy is active for rotation')),
                ('last_ok_at', models.DateTimeField(blank=True, help_text='Last time this proxy was successfully used', null=True)),
                ('fail_count', models.IntegerField(default=0, help_text='Number of consecutive failures')),
                ('meta_json', models.JSONField(blank=True, help_text='Additional metadata for this proxy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'ordering': ['fail_count', '-last_ok_at'],
                'indexes': [models.Index(fields=['is_active'], name='proxy_proxy_is_acti_3b2c6b_idx'), models.Index(fields=['fail_count'], name='proxy_proxy_fail_co_25e6b0_idx'), models.Index(fields=['last_ok_at'], name='proxy_proxy_last_ok_975657_idx'), models.Index(fields=['is_active', 'fail_count'], name='proxy_proxy_is_acti_f01f30_idx')],
            },
        ),
    ]
