# Generated by Django 4.2.23 on 2025-07-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_urls_json', models.JSONField()),
                ('settings_json', models.JSONField(blank=True, null=True)),
                ('parse_rules_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiders', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('project', 'name')},
            },
        ),
    ]
